= Bags

Bags have three types of files. For basegame heists, you can find most of these in `/Prototype/Blueprints/Bags`.

[cols=`1,3`]
|===
|File |Purpose

|`BP_Interactable(BAG)`
|The item before it is a bag (aka the money bundle)

|`BP_(BAG)`
|The bag itself

|`DA_(BAG)`
|Holds the information pertinent to the bag for spawners and other classes.
|===

== Spawning bags

You can spawn in physical bags, for equipment or other means using the `SBZBagSpawner` class.

Set the `Bag Type to Spawn` variable to signify what bag data asset to spawn.

== Bag trigger volumes

`SBZBag Trigger Volume` is used for respawning, securing, or destroying bags. 

Setting trigger mode to `Secure and Destroy` will secure the bag itself and is typically what is used when securing bags.

`Destroy` can be used for things such as equipment like setting up thermite.

`Teleport` is used along with the `SBZ Respawn Point` to teleport bags, set the `Bag Teleport Point` to a `SBZRespawn Point` to have it teleport there automatically. This is used for when bags go out of bounds and you need to reset it back to the playable space.

Using the filters, you can filter exact bags. Just hit the + on the filter type and add in the DA of the bag you only want to be able to trigger this volume.

You can use the `Target` to set a an amount of bags to be seccured in this volume before executing. This can be used for either having it auto disable when you've hit that target via the `Disable on Complete`, or if you'd like to tell when a certain amount of bags have been secured using the `Add on Complete` event.

Use `On bag entered or Secured` combined with an `Add Progress` function call on an objective to count bags in the HUD. See xref:objectives.adoc[Objectives] for more.

== Bag drop points

`SBZBag Drop point` signify where cops go after they've picked up a bag. Simply place a point down in the nav mesh, and cops will automatically go to this location.