= Bags

There are three types of bag files. For base game heists, most of these are in `/Prototype/Blueprints/Bags`.

[cols="1,3"]
|===
|File |Purpose

|`BP_Interactable(BAG)`
|The item before it is a bag (aka the money bundle)

|`BP_(BAG)`
|The bag itself

|`DA_(BAG)`
|Holds the information pertinent to the bag for spawners and other classes.
|===

== Spawning bags

You can spawn physical bags, for equipment or other purposes, using the `SBZBagSpawner` class.

Set the `Bag Type to Spawn` variable to choose which bag data asset to spawn.

== Bag trigger volumes

`SBZBag Trigger Volume` is used for respawning, securing, or destroying bags.

Setting the trigger mode to `Secure and Destroy` secures the bag, and is the mode typically used for securing bags.

`Destroy` can be used for equipment, such as when you set up thermite.

`Teleport` is used together with the `SBZ Respawn Point` to teleport bags. Set the `Bag Teleport Point` to a `SBZRespawn Point` and bags will teleport there automatically. This is used when bags go out of bounds and need to be reset to the playable space.

Use the filters to restrict the volume to specific bags. Select the + on the filter type and add the DA of the bag that should be able to trigger this volume.

Use `Target` to set the number of bags that must be secured in this volume before it executes. You can use `Disable on Complete` to disable the volume automatically once the target is reached, or use the `Add on Complete` event to detect when a certain amount of bags have been secured.

Combine `On bag entered or Secured` with an `Set Progress` function call on an objective to count bags in the HUD. See xref:objectives.adoc[Objectives] for more.

== Bag drop points

`SBZBag Drop point` marks where cops go after they have picked up a bag. Place one on the nav mesh and cops will go to it automatically after they have picked up a bag.
