= Create Your First Heist

== Creating your first heist

CrimeForge provides a basic heist template. You can create a mod with the template via:

- Clicking the Dallas mask at the top of the editor
- Clicking `Create mod`
- Clicking `Heist Template`

Then enter a name for your mod.

To create a heist without the template, start from a blank mod template and follow the information below.

== Inside this template

See xref:crimeforge:templates.adoc[Templates] for the standard template assets.

=== `DA_Heist_(modname)`

The most important file in the template. This data asset holds the basic information you see for the heist in the menus and, in some cases, during the heist itself. Here you set the name of your heist, its description, time of day, and location. It also holds other details, such as the heist banner image.

[IMPORTANT]
====
Currently, if you experience issues loading into the heist and get a `failed to fetch data` error, you may need to change the name of your `LVL_(modname)` to match the name of a vanilla PAYDAY 3 heist codename.

See xref:inspect-vanilla-heists.adoc[Inspecting Vanilla Heists] for all vanilla codenames.
====

== Launching your heist

See xref:crimeforge:packaging.adoc[Forge] for the full Forge workflow before continuing.

Once in game, start a solo mode heist, then change the filter until it says `Custom Heists`.

Your heist should now be listed, provided you entered a name in the `DA_Heist_(modname)`. Click the heist to launch it.

You just made your first heist!

Follow the link below to make sure your heist is set up for the heist game mode, and more.

* xref:world-settings.adoc[World Settings]
