= Intro Sequences

Custom heists can also have custom intro sequences.

If you still need help, you can follow this video to set it up: https://www.youtube.com/watch?v=F_MLP3XvCQI

== Master sequence and level setup

Start by creating a master sequence, which holds all of your cinematic shots. For easier management, it is recommended to create a new empty level that is streamed into the main custom heist level.

. Set the world settings Game Mode of the empty level to `BP_HeistGameMode`.
. Open the level blueprint and open the Class Settings tab.
. Change the parent class to `SBZLevelScriptActor`, which gives access to many useful PAYDAY 3 functions.

== Creating the shots

In the editor, click the Cinematics tab on the top toolbar (near Blueprints) and create a new master sequence. Give it a name and a number of shots, adjust any other settings as desired, then click Create Master Sequence.

The master sequence automatically creates several level sequence shots. Go through each shot and adjust the camera animation to your liking.

[IMPORTANT]
====
The camera cuts for each shot must fill the full length of the sequence, or the animation will not work.
====

== Intro logic

Once all shots are adjusted and the master sequence looks good, you can set up the logic. Open the level blueprint and override the `Intro Sequence Changed` event.

If the intro has started:

* Set the game to cinematic mode.
* Hide all outlines.
* Play the master sequence.
* Bind an event to the sequence player's finish event to end the intro sequence. This calls the `End Intro Sequence` function from the `SBZLevelScriptActor` class, resets cinematic mode, and unhides all outlines.

If the intro has not started (meaning it is changing from playing to finished):

* Unbind the on finished event.
* Stop the sequence player.
* Reset cinematic mode and unhide the outlines.

== Streaming the sublevel

If you handle the intro/outro logic within a sublevel, you need to stream that level in from your main level. This can be done in blueprints, or by setting the sublevel to Autoloaded. In your main level blueprint, use the `BlackScreenStarted` event to stream in the intro/outro sublevel. Make sure you select the correct level.

== Heist data asset

Finally, return to your heist data asset and make sure `Has Intro Sequence` is set to true.
