= Intro Sequences

Custom heists can also have custom intro sequences. It is recommended that you learn a little about UE5's sequencer and the basics of making cinematics before starting.

If you still need help, you can follow this video to get it setup https://www.youtube.com/watch?v=F_MLP3XvCQI

== Master sequence and level setup

To get started with the intro, you need to create a master sequence. This will hold all your cinematic shots. For better management and workflow purposes, it is recommended to create a new empty level that will be streamed into the main custom heist level. Ensure the world setting of this empty level is set to `BP_HeistGameMode`. Now open the level blueprint, open the class settings tab and change the parent class to `SBZLevelScriptActor` class. This will give us access to many useful PD3 related functions.

== Creating the shots

Back in the editor, click the Cinematics tab on the top toolbar (near Blueprints) and create a new master sequence. Give it a name and a number of shots (and adjust any other settings to your desires) then click Create Master Sequence.

You should now have a few new level sequence shots that were auto created with the master sequence. Simply go through each shot and adjust the camera animation to your liking.

It is important that the camera cuts for the shot fills the full length of the sequence or the animation won't work.

== Intro logic

Once you have all shots adjusted and the master sequence looks good, you can set up the logic. Open the level blueprint and override the `Intro Sequence Changed` event. If the intro has started, you can set the game to cinematic mode, hide all outlines and play the master sequence. You should also bind an event on the sequence player on the finish event that will handle ending the intro sequence. This will call the `End Intro Sequence` function from the `SBZLevelScriptActor` class along with also resetting the cinematic mode and unhiding all outlines. If the intro hasn't started (meaning its changing from playing to finished), you can unbind the on finished event, stop the sequence player and reset the cinematic mode and unhide the outlines.

== Streaming the sublevel

If you are handling the intro/outro logic within a sublevel, you will need to stream the level in your main level. This can either be done in blueprints or by setting the sublevel to be Autoloaded. In your main level blueprint, on BlackScreenStarted event, you can load stream the intro outro sublevel like this: (make sure you select the correct level)

== Heist data asset

Now go back to your heist data asset and ensure `Has Intro Sequence` is set to true.
