= Life Actions

Life actions are a wide range of actions that AI perform around the heist, each resulting in an animation.

Examples of life actions include:

- A civilian thrown into the eye scanner bending down to scan their eyes
- Guards or civilians sitting or walking idly during stealth heists
- Holding a prop while idle (i.e., a phone)
- Two civilians talking

[NOTE]
====
This page is a current work in progress.
====

== Giving a life action

* Place a blueprint in the level and have a life action reference it (typically for movement)
* Within the `PawnSpawn`, set the Action to `SBZAIAction Life Action` and set the gameplay effect class to the animation you want.

=== Patrols

. Spawn `SBZPatrol Points` around the level.
. Set the pawn spawn action to `SBZAIAction Patrol`.
. Set the Action order to `SBZAIOrder Patrol`, then set the Start point to the start of the patrol.

Inside each patrol point, you set what the next patrol point is, whether it randomizes, and how long the person waits at the location.

=== Life action settings

See xref:world-settings.adoc[World Settings] for adding the life action data asset, which loads life action animations.
