= Player Triggers

== Player trigger volume

`SBZPlayerTriggerVolume` is Used for when the player enters an area. 
You can see when players begin or end touching the volume itself by the Player Pawn Begin/End Overlapping respectively.

`Overlapping all player pawns` checks for all players instead of just one.

== Player Trigger Voice Volume

Just like the regular player trigger, except this trigger is for ease of having player specific voicelines play.

set the `Dialog` to play shade, twitch, or shade voicelines.

Set the `Comment` to play heister specific voicelines.

== Escape trigger

The trigger volume to initiate an escape is not the Player trigger volume. This volume is called `SBZPlayerEscapeVolume`. 

You can signify how long the escape duration is, and if the volume disables when complete.

=== Ending the mission

. For Escape trigger use event `On Escape Timer Done`
. After this go to a `Request mission End` node
. Set the target set to a `Get Game State machine` Node
. From Request data hit make `SBZEndMissionRequestData` and set `Mission Result` to Success

=== Failing the mission

If you want to fail a mission instead, you can use the same `Request Mission End` layout but instead set `Mission Result` to `Failed`
