= Player Triggers

== Player trigger volume

`SBZPlayerTriggerVolume` detects when a player enters an area.

Use the Player Pawn Begin Overlapping and Player Pawn End Overlapping events to detect when players enter or leave the volume.

`Overlapping all player pawns` checks for all players instead of just one.

== Player trigger voice volume

This works like the regular player trigger, but is intended for playing player-specific voicelines.

Set the `Dialog` to play Bile, Twitch, or Shade voicelines.

Set the `Comment` to play heister-specific voicelines.

== Escape trigger

Escapes use a separate volume, `SBZPlayerEscapeVolume`, rather than the player trigger volume.

You can set the escape duration and whether the volume disables when complete.

Use the `BP_MarkerZone` blueprint for the highlight for the escape zone, or bag secure zones.

[NOTE]
====
`BP_MarkerZone` is purely for decoration and does not have logic such as escaping, or securing of bags.
====


=== Ending the mission

. Use the `On Escape Timer Done` event from the `SBZPlayerEscapeVolume`.
. After this, add a `Request Mission End` node.
. Set its target to a `Get Game State machine` node.
. From `Request Data`, select `Make SBZEndMissionRequestData` and set `Mission Result` to `Success`.

=== Failing the mission

To fail the mission instead, use the same `Request Mission End` layout, but set `Mission Result` to `Failed`.
