= World Settings

World Settings controls the level state as a whole. Starbreeze has a custom world settings class called `SBZWorldSettings`. 

In the modkit this is already listed as the default World settings in the project settings but incase you can see it when viewing the world settings tab from a level.

=== Finding the PD3 World Settings

. Head to the Project Settings
. Search for `World Settings`
. Change the default class to `SBZWorldSettings`

If you can't see SBZWorld settings, ensure you are using the modkit and you've exported the jmap.

[IMPORTANT]
====
Pay attention to the important tags such as this for what options are required for you heist to function.
====

== Surface types

Changes the impact hits from bullets on materials. Typically leave this as none.

== Music

The following variables all control the music in the heist, although typically these are left default other than `Music Event`, you can edit them if you'd like.


- `Music Event` controls which song will play during the heist. You can use a base game song or your own.
- `Stop Music` Play this event when `Get Music Manager -> Stop Music` function is played
- `Start Music on Begin Play` Default is on. Otherwise use `Get Music Manager -> Play Music` to start a song.

== Negotiation

The following variables control what happens when the alarm goes off.

- `Skip Negotiation` Skips the negotiation phase
- `Skip First Responders` Skips waiting for first responders to arive on scene. Used in Road rage to immedietely go to Anticipation/Negotiation phase

== Key Item Data map

Important Map to correlate gameplay item pickups to HUD items that show up on each player. If you are placing pickup items but they do not appear on the player, this is the setting you need to fix.

- `Key` Your Gameplay Tag correlated to the asset you are picking up. Most will be in the `Item` category
- `Value` The UI Data Asset that has the UI texture. 

Both Tags and the `SBZKeyItemData` can be made into custom Key items.

== Managers

An important section that controls many factors with the level itself. Without some of these, these features will not work.

=== Assault manager
Controls everything assault related. In 3.9 Starbreeze changed to using small, medium, big, & huge variants to control the intensity of assault spawns in the heist.

While it is recommended to use one of the default settings, if you use you may copy an uncooked version of one of these assets and change some of the values.

- `* Phase Duration Seconds` Controls how long each phase lasts (Anticipation, Build, Regroup)
- `Difficulty Settings Array` Changes various difficulty settings such as squads/cops that can spawn per assault wave, difficulty increase per assault wave, time reduction on certain phases across assault waves.
- `Types to ignore During First Build` Enemy types to ignore before first assault begins

See xref:inspect-vanilla-heists.adoc[Inspecting Vanilla Heists] for a table of code name to heists.

[NOTE]
====
While the names are mostly self explanatory, the remaining settings have not been verified.
====

[IMPORTANT]
====
This manager is required for the game to run stable.
====

=== Negotiation manager

Affects settings related to the negotiation phase and civilian killed penalty per difficulty. Similar to Assault Manager where it is recommended to use a Vanilla data asset, but if you want copy an uncooked version to your local mod folder before editing.

[NOTE]
====
While the names are mostly self explanatory, these settings have not been verified.
====

[IMPORTANT]
====
This manager is required for the game to run stable.
====

=== Civilian manager
Controls the automatic infinite spawning of roaming civilians that walk around on a heist such as `Syntax Error`, `No Rest for the Wicked`, and more. Not used to designate regular civial spawns.

[NOTE]
====
While the names are mostly self explanatory, these settings have not been verified.
====

=== Traffic manager
This manager controls the flow of automatic infinite spawning vehicles, such as the cards on `No Rest for the Wicked`.

They are also used to control the spawning of SWAT Vans and First Responder vehicles.

[NOTE]
====
While the names are mostly self explanatory, these settings have not been verified.
====


=== Life action settings
Starbreeze has one Data Asset available. This asset loads the requirements to run certain life actions. 

`/Gameplay/Data/LifeActionSystem/LoadingSettings/DA_LA_GenericLevel_LoadingSettings`

=== Small/Phone talk Collections
Controls what conversations civilians are able to have when being idle around the heist during stealth.

== Other settings

There is a lot of default unreal information in here that you can look up separately such as `Lightmass` which can be helpful for your map. SBZ typically keeps this default though.

== Game mode

Set the gamemode to `BP_HeistGameMode` to ensure numerous important classes are loaded correctly.

[IMPORTANT]
====
Without it, the game can not be loaded correctly in your heist and you may be prone to crashes.
====
