= World Settings

World Settings controls the level state as a whole. Starbreeze has a custom world settings class called `SBZWorldSettings`.

In the modkit, this is already the default class in the Project Settings. If you can't see it in a level's World Settings tab, follow the steps below.

== Finding the PAYDAY 3 World Settings

. Head to the Project Settings.
. Search for `World Settings`.
. Change the default class to `SBZWorldSettings`.

If you can't see `SBZWorldSettings`, ensure you are using the modkit and you've exported the jmap.

[IMPORTANT]
====
Boxes like this one mark options that are required for your heist to function. Such as setting it up so you can see the `SBZWorldSettings`.
====

== Music

The following variables control the music in the heist. They are typically left at their defaults other than `Music Event`, but you can edit them if you'd like.

- `Music Event` controls which song will play during the heist. You can use a base game song or your own.
- `Stop Music` plays this audio event when the `Get Music Manager -> Stop Music` function is called.
- `Start Music on Begin Play` is on by default. Otherwise, use `Get Music Manager -> Play Music` to start a song.

== Heist settings

The following variables control what happens during the heist

- `Skip Negotiation` skips the negotiation phase.
- `Skip First Responders` skips waiting for first responders to arrive on scene. Used in Road Rage to go immediately to the Anticipation/Negotiation phase.
- `Start in Casing` starts the player in casing mode.
- `AICrew Start in Casing` starts the AICrew in casing mode.
- `Start with AICrew` disables AICrew.
- `Can Crew Shoot Steet Cops` is off by default and allows the crew to shoot at guards during negotiation. Used in `Boys in Blue` since the beat cops are actually police officers in that heist.

== Key Item Data Map

This important map correlates gameplay item pickups to the HUD items that show up on each player. If you are picking up items but they do not appear on the HUD, this is the setting you need to fix.

- `Key` is the Gameplay Tag that corresponds to the asset you are picking up. Most will be in the `Item` category and clearly indicate the item in their name.
- `Value` is the UI Data Asset that has the UI texture.

== Managers

This section controls many aspects of the level. Some of these features will not work unless their manager is set.

=== Assault manager

Controls everything assault-related. In 3.9, Starbreeze changed to using small, medium, big, and huge variants to control the intensity of assault spawns in the heist.

Using one of the default settings is recommended. To edit the values, copy an uncooked version of one of these assets to your mod folder. See xref:creating-mods:asset-replacements.adoc#_convert_the_cooked_asset[Convert to Uncooked] for how to do this.

- `* Phase Duration Seconds` controls how long each phase lasts (Anticipation, Build, Regroup).
- `Difficulty Settings Array` changes various difficulty settings, such as the squads/cops that can spawn per assault wave, the difficulty increase per assault wave, and the time reduction on certain phases across assault waves.
- `Types to ignore During First Build` lists enemy types to ignore before the first assault begins.

[NOTE]
====
While the names are mostly self-explanatory, the remaining settings have not been verified.
====

[IMPORTANT]
====
This manager is required for the game to be stable.
====

=== Negotiation manager

Affects settings related to the negotiation phase and the civilian-killed penalty per difficulty. As with the assault manager, using a vanilla data asset is recommended. To edit the values, copy an uncooked version to your mod folder first. See xref:creating-mods:asset-replacements.adoc#_convert_the_cooked_asset[Convert to Uncooked].

[NOTE]
====
While the names are mostly self-explanatory, these settings have not been verified.
====

[IMPORTANT]
====
This manager is required for the game to be stable.
====

=== Civilian manager

Controls the automatic, infinite spawning of roaming civilians that walk around a heist, such as in `Syntax Error` and `No Rest for the Wicked`. It is not used to designate regular civilian spawns.

[NOTE]
====
While the names are mostly self-explanatory, these settings have not been verified.
====

=== Traffic manager

Controls the flow of automatically and infinitely spawning vehicles, such as the cars in `No Rest for the Wicked`.

It is also used to control the spawning of SWAT vans and first responder vehicles.

[NOTE]
====
While the names are mostly self-explanatory, these settings have not been verified.
====

=== Life action settings

Starbreeze has one data asset available. This asset loads the requirements to run certain life actions.

`/Gameplay/Data/LifeActionSystem/LoadingSettings/DA_LA_GenericLevel_LoadingSettings`

=== Small/phone talk collections

Controls the conversations civilians can have while idle during stealth.

== Other settings

This tab also contains many standard Unreal Engine settings, such as `Lightmass`, which can be useful for your map. Starbreeze typically leaves these at their defaults.

== Game mode

Set the game mode to `BP_HeistGameMode` to ensure numerous important classes are loaded correctly.

[IMPORTANT]
====
Without it, the heist may not load correctly and is more likely to crash.
====
